config/routes.rb
Rails.application.routes.draw do
  resources :daily_reports do
    collection do
      get 'monthly_output'
    end
  end

  devise_for :users

end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
  extend Forwardable
  include Enumerize

  enumerize :work_status, in: [:attendance, :paid_vacation], default: :attendance

  after_initialize :calculate_work_time, unless: :new_record?

  def_delegators :@work_time, :early_work_hours, :normal_work_hours, :overtime_work_hours, :late_work_hours

  validates :start_datetime, presence: {if: ->(r){ r.work_status.attendance? }}
  validates :end_datetime,   presence: {if: ->(r){ r.work_status.attendance? }}
  validates :work_status,    presence: true

  def start_datetime=(time)
    super("#{date} #{time}") if time.present?
  end

  # def start_datetime
  #   super.try(:strftime, "%H:%M")
  # end

  def end_datetime=(time)
    super("#{date} #{time}") if time.present?
  end

  # def end_datetime
  #   super.try(:strftime, "%H:%M")
  # end

  private
  def calculate_work_time
    @work_time = WorkTime.new(start_datetime, end_datetime) if start_datetime.present? && end_datetime.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: [:show, :edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json
  def index
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.today
    @daily_reports = DailyReport.where("date >= ? and date <= ?", @date.beginning_of_month, @date.end_of_month)
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
  end

  # GET /daily_reports/new
  def new
    report_date ||= params[:date]
    unless @daily_report = DailyReport.find_by(date: report_date)
      @daily_report = DailyReport.new(date: report_date)
    end

  end

  # GET /daily_reports/1/edit
  def edit
  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to daily_reports_path, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_reports/1
  # PATCH/PUT /daily_reports/1.json
  def update
    respond_to do |format|
      if @daily_report.update(daily_report_params)
        format.html { redirect_to daily_reports_path, notice: 'Daily report was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_report }
      else
        format.html { render :edit }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_reports/1
  # DELETE /daily_reports/1.json
  def destroy
    @daily_report.destroy
    respond_to do |format|
      format.html { redirect_to daily_reports_url, notice: 'Daily report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_report
      @daily_report = DailyReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_report_params
      params.require(:daily_report).permit(:user_id, :date, :start_datetime, :end_datetime, :work_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/views/daily_reports/_form.html.slim
= simple_form_for(@daily_report, wrapper: "horizontal_form", :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date, as: :hidden
    = f.input :start_datetime, as: :string, input_html: {value: @daily_report.start_datetime}
    = f.input :end_datetime, as: :string, input_html: {value: @daily_report.end_datetime}
    = f.input :work_status, as: :radio_buttons, item_wrapper_class: "radio-inline"

  .form-actions
    = f.button :submit, class: "btn btn-primary"

  javascript:
    $(function(){
      $("#daily_report_start_datetime").clockpicker({autoclose: true});
      $("#daily_report_end_datetime").clockpicker({autoclose: true});
      $('#daily_report_date').datepicker({
        format: 'yyyy/mm/dd',
        language: 'ja',       // カレンダー日本語化のため
        autoclose: true
      });
    });

app/views/daily_reports/edit.html.slim
h1 Editing daily_report

== render 'form'

= link_to 'Show', @daily_report
'|
= link_to 'Back', daily_reports_path

app/views/daily_reports/index.html.slim
h1 Listing daily_reports

ul.pager
  li.previous = link_to "前月", daily_reports_path(date: @date.prev_month)
  li.next = link_to "翌月", daily_reports_path(date: @date.next_month)
.panel.panel-default
  .panel-heading = @date.strftime("%Y年%m月")
  table.table
    thead
      tr
        th = DailyReport.human_attribute_name(:date)
        th = DailyReport.human_attribute_name(:start_datetime)
        th = DailyReport.human_attribute_name(:end_datetime)
        th = DailyReport.human_attribute_name(:work_status)
        th = DailyReport.human_attribute_name(:normal_work_hours)
        th = DailyReport.human_attribute_name(:overtime_work_hours)
        th = DailyReport.human_attribute_name(:late_work_hours)

    tbody
      - (@date.beginning_of_month..@date.end_of_month).each do |date|
        tr
          td = link_to date, new_daily_report_path(date: date)
          - if d = @daily_reports.find {|r| r.date == date }
            td = d.start_datetime.try(:strftime, '%H:%M')
            td = d.end_datetime.try(:strftime, '%H:%M')
            td = d.work_status.text
            td = d.normal_work_hours.round(2) if d.work_status.attendance?
            td = d.overtime_work_hours.round(2) if d.work_status.attendance?
            td = (d.early_work_hours + d.late_work_hours).round(2) if d.work_status.attendance?
          - else
            td[colspan=6]

= link_to "出力", monthly_output_daily_reports_path(date: @date), class: "btn btn-primary"

app/views/daily_reports/new.html.slim
h1 New daily_report

== render 'form'

= link_to 'Back', daily_reports_path

app/views/daily_reports/show.html.slim
p#notice = notice

p
  strong User:
  = @daily_report.user_id
p
  strong Date:
  = @daily_report.date
p
  strong Start datetime:
  = @daily_report.start_datetime
p
  strong End datetime:
  = @daily_report.end_datetime
p
  strong Work status:
  = @daily_report.work_status

= link_to 'Edit', edit_daily_report_path(@daily_report)
'|
= link_to 'Back', daily_reports_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ElvenSword
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body[style="background-color: rgb(241, 242, 246);"]
    #container
      .row
        p.notice
          = notice
        p.alert
          = alert
      .col-sm-12
        = yield